spring:
  profiles:
    active: @project.active@
  redis:
    host: ${BELUGA_REDIS_HOST:localhost}
    password: ${BELUGA_REDIS_PASSWORD:}
swagger:
  base-package: cn.dhbin.beluga
  version: @project.version@
mybatis-plus:
  type-enums-package: cn.dhbin.beluga.*.model.enums
