spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    username: ${BELUGA_DB_USERNAME:sa}
    password: ${BELUGA_DB_PASSWORD:sa}
    url: jdbc:h2:file:${BELUGA_DB_NAME:./beluga}